apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: haproxy
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/haproxy@sha256:94f02711be1e15a1a0fcd8f3db70b4247ac7e8ac1b9992c3b53914bb8a9ea43e
        name: container-image
        resources: {}
status: {}
